# Use root/example as user/password credentials
version: '3.1'

services:

  # if we'd want to run the actual capture in docker as well...
  #rasberry_data_capture:
  #  build: .
  #  devices:
    # allow container to access USB0
  #  - "/dev/ttyUSB0:/dev/ttyUSB0"

  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27018:27017
    volumes:
      - /srv/mongo/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: b7d7e9d16bef48e4cb78353214792814

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: b7d7e9d16bef48e4cb78353214792814
      ME_CONFIG_BASICAUTH_USERNAME: rasberry
      ME_CONFIG_BASICAUTH_PASSWORD: 078c9cfbac66b9675de8935f7030ce06
